on: push
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install candran
        run: luarocks install candran
      - name: Candran to Lua [1/2]
        run: bash ./.scripts/CandranToLua.sh
      - name: Candran to Lua [2/2]
        run: bash ./.scripts/CandranToLua.sh
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: lint
        uses: Roang-zero1/factorio-mod-luacheck@master